site_name: Stan's Static Site
site_description: A static website about Stan the Snakes's adventures created using Python's MkDocs.
site_author: Stan the Snake
repo_url: https://github.com/python-spokane/stans-static-site

nav:
  - Home: 'index.md'
  - Adventures:
    - Microsoft: 'adventures/microsoft.md'
    - Amazon: 'adventures/amazon.md'

markdown_extensions:
  - attr_list
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

theme:
  name: material
  icon:
    logo: material/snake
  favicon: img/favicon.svg
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tracking

extra_css:
  - stylesheets/extra.css
